name: text_metrics
description: Biblioteca para métricas e análise de texto em Dart.
version: 0.0.1
homepage: https://github.com/Isac-Eugenio/text_metrics
repository: https://github.com/Isac-Eugenio/text_metrics

environment:
  sdk: ">=3.10.7 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
